README.md
app/screens/LoginScreen/loginScreen.js
app/screens/LoginScreen/style.js

Added animated button to login with Facebook feature. UI only.

Added Login with Facebook button 

---

app/screens/ChatListScreen/chatListScreen.js
app/screens/ChatListScreen/style.js

This PR fixes #24 by changing the font color in the `Messages` section of the app. This small fix will make both subheaders more readable 😄 
Screenshot:

Change Font color in Messages Tab

---

README.md
package-lock.json

This PR is related to issues #35 #43

update readme.md file

---

app/components/ConversationBanner/style.js
app/components/HeaderNavigationBar/styles.js
app/components/NotificationBanner/style.js
app/screens/ChatListScreen/style.js
app/screens/MapScreen/style.js
app/screens/NotificationScreen/style.js
app/screens/ProfileScreen/profileScreen.js
app/screens/ProfileScreen/style.js
package-lock.json

The Landscape Orientation view of all the Screens had UI Issue and I fixed in the Map and the Notification Screens. Now its Look good in both Portrait and the Landscape Orientations.

Fixed the UI Issue of Landscape View.

---

App.js
app/screens/ForgotPasswordScreen/forgotPasswordScreen.js
app/screens/ForgotPasswordScreen/style.js

Created the Forgot password Screen

---

.gitignore
config/config.example.js
package-lock.json

This PR is related to the issue number #13

Add firebase configuration file

---

.vscode/settings.json
App.js
android/.project
android/.settings/org.eclipse.buildship.core.prefs
android/app/.classpath
android/app/.project
android/app/.settings/org.eclipse.buildship.core.prefs
android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/go_social/MainActivity.java
android/app/src/main/java/com/go_social/MainApplication.java
android/app/src/main/res/values/strings.xml
android/settings.gradle
app/screens/LoginScreen/loginScreen.js
app/screens/LoginScreen/style.js
ios/Go_social.xcodeproj/project.pbxproj
package.json

This PR is related to facebook sdk configuration with android application.
This PR is solving the issue with integrating the facebook sdk with android app when adding facebook login to the go-social application.
react-native run-android

add facebook sdk and configure it with android

---

.gitignore
.travis.yml
__tests__/login-test.js
package.json

This PR provides a sample test case and a Travis CI integration for the project
This PR solves this issue #42 
Testing Units testings for now
**Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.**
npm test
closes #42 

CI with travis

---

App.js
app/screens/ForgotPasswordScreen/forgotPasswordScreen.js
app/screens/LoginScreen/loginScreen.js

Created the Email password Reset Functionality and created the Skip Login button in order to ease the development.
Issue #46 and the Developer has to log to the system to view the inside of the app so that created the skip login button
Unit Testing Up to Now
Put `closes #46 ` in your comment and commit message to auto-close the issue that your PR fixes (if such).

Creted the Skip Login button and the Forgot password functionality

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
App.js
README.md

Code quality enhancements - From codacy suggestions.
To improve the code quality and the readability of the code.

code quality enhancements

---

app/screens/LoginScreen/loginScreen.js
app/screens/SignupScreen/signupScreen.js
app/screens/SignupScreen/style.js

Add sign up with facebook to sign up view
Same functionality in the login view was added to sign up view

add sign up with facebook to Go-social

---

app/screens/ForgotPasswordScreen/forgotPasswordScreen.js
app/screens/ForgotPasswordScreen/style.js
app/screens/LoginScreen/loginScreen.js
app/screens/LoginScreen/style.js
app/screens/SignupScreen/signupScreen.js
app/screens/SignupScreen/style.js

Fixed the UI of LoginScreen, SignUpScreen and The ForgotPasswordScreen in Landscape View. As well enhance the Format of the Codes of Those Screens 
Previously The view was good for the portrait and it has the Ui issue in the Landscape View. Issue #47 
Unit Test Up to Now
Put `closes #47 ` in your comment and commit message to auto-close the issue that your PR fixes (if such).

Fixed UI Issues Of the LoginScreen, SignUpScreen and The ForgotPasswordScreen in Landscape View.  

---

app/components/HomePostComponent/HomePostComponent.js

In previous version there was no any social media actions -> like, comment, share. They are added through this PR
Make the UI more attractive and easy to understand

add like comment share buttons to home components

---

README.md
app/screens/MapScreen/Directions/directions.js
app/screens/MapScreen/Search/searchView.js
config/config.example.js

This PR is related to #33 #34 #32 #28 #14 #16 
The installation and running Go-social is updated through readme.md file

Update the readme.md file to latest

---

README.md
app/screens/LoginScreen/loginScreen.js
app/screens/SignupScreen/signupScreen.js
app/screens/SignupScreen/style.js
package.json

Modified the README.md File
The File didn't properly mentioned how to run the application 

Updated the README.md

---

android/app/src/main/AndroidManifest.xml
app/screens/ProfileScreen/profileScreen.js
app/screens/ProfileScreen/style.js

This pull request contains functions to profile page to save and retrieve date with Firebase Realtime Database.
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Add profile Firebase saving!

---

App.js
app/components/ConversationBanner/conversationBanner.js
app/components/ConversationBanner/style.js
app/components/HeaderNavigationBar/HeaderNavigationBar.js
app/components/HeaderNavigationBar/styles.js
app/components/HomePostComponent/styles.js
app/components/NotificationBanner/notificationBanner.js
app/components/SuggestionsCardView/style.js
app/components/SuggestionsCardView/suggestionsCardView.js

Code quality enhancement suggestion by codacy

codacy code quality enhancements

---

app/components/ConversationBanner/conversationBanner.js
app/components/ConversationBanner/style.js
app/components/Rating/rating.js
app/components/Rating/readOnlyRating.js
app/components/SuggestionsCardView/suggestionsCardView.js
app/screens/ChatListScreen/chatListScreen.js
app/screens/HomeScreen/homeScreen.js

Created the Rating Component
Rating component was not There So I Created the Rating component
Unit Testing

Creted the Rating Component

---

app/components/DraggableMarker/draggableMarker.js
app/components/DraggableMarker/styles.js
app/screens/MapScreen/mapScreen.js
app/screens/MapScreen/style.js

This PR is related to the issue number #83 
Now user can add a marker by dragging the marker
Put `closes #83 ` in your comment and commit message to auto-close the issue that your PR fixes (if such).

Add draggable marker map component

---

App.js
app/components/MessageComponents/friendMessage.js
app/components/MessageComponents/myMessage.js
app/components/MessageComponents/style.js
app/components/ModalHeaderNavigationBar/modalHeaderNavigationBar.js
app/components/ModalHeaderNavigationBar/styles.js
app/components/SuggestionsCardView/style.js
app/screens/ChatListScreen/chatListScreen.js
app/screens/MessaginScreen/messaginScreen.js
app/screens/MessaginScreen/style.js
app/screens/NewPostScreen/NewPostScreen.js

Created New Components and Created the Navigation to the MessaginScreen and Finished the UI. Updated the Stack of App.js With the New Screen. 
This is a part of the issue #82 
Unit Testing

Created New comoponents, Messaging UI and Updated App.js 

---

app/screens/ProfileScreen/profileScreen.js
app/screens/SignupScreen/signupScreen.js

Fixed Data Retrieving and Issue in Profile
Values for the textInputs in the profile Screen was Not set correctly
Unit Testing

Fixed Data Rertring Issue in Profile

---

app/components/ConversationBanner/conversationBanner.js
app/components/ConversationBanner/style.js
app/components/SuggestionsCardView/style.js
app/screens/ChatListScreen/chatListScreen.js
app/screens/MessaginScreen/messaginScreen.js
app/screens/MessaginScreen/style.js

Created the Back-end Functionality of the Chat
Only the UI s were there nothing was implemented in back-end
Unit Test
Put `closes #82 ` in your comment and commit message to auto-close the issue that your PR fixes (if such).

BackEnd Functionality Of the Chat

---

app/screens/ProfileScreen/profileScreen.js

Add a feature to upload a profile photo for profile section of the app
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

add profile photo Upload

---

app/screens/ProfileScreen/profileScreen.js

Fix Autoupdate profile picture on select and profile details for guest user
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Fix some profile Bugs

---

app/screens/ChatListScreen/chatListScreen.js
app/screens/LoginScreen/loginScreen.js
app/screens/MessaginScreen/messaginScreen.js
app/screens/ProfileScreen/profileScreen.js

Fixed the Issue of Logout and Fixed the Issue of rendering the Users to the Chat Screen and Error handling in the Send Messages 
Error of a state was there when pressing the logout , Users were Not Rendered properly to the chat Screen and there gave errors when press the send message icon in hardcode components
Unit Testing

Fixed Some Issues In LogOut and in Chat

---

.travis.yml
Docs/src/App.test.js
README.md
__tests__/login-test.js
config/config.example.js
package.json

This PR is because of updating the readme file and adding missing folder
There were some issues with readme file

add missing config folder and update readme.md

---

app/components/HomePostComponent/HomePostComponent.js
app/screens/ProfileScreen/profileScreen.js
app/screens/ProfileScreen/style.js

i tried to fixed the design on the profile there a few design inconsistency like when the device was rotated the margin where set only to left which made it not look nice. i also moved the sign out button to the bottom of the page before the save button
in my design i maintain the same color pattern and i also thought adding a label before each field would help the user better understand what information they are required to enter in that field 
i think it makes it more user friendly and for the sign out button i believe when a user first opens the profile they don't necessary want to see the sign out button first instead they might want to change or correct their information that's why i put it at the bottom …

Change a bit the design of the profile page also added sharing functionality from this issue #93

---

ios/Go_social.xcodeproj/xcshareddata/xcschemes/Go_social-tvOS.xcscheme
ios/Go_social.xcodeproj/xcshareddata/xcschemes/Go_social.xcscheme
ios/Go_social/AppDelegate.h
ios/Go_social/AppDelegate.m
ios/Go_social/Images.xcassets/AppIcon.appiconset/Contents.json
ios/Go_social/Info.plist
ios/Go_social/main.m
ios/Go_socialTests/Go_socialTests.m
ios/Go_socialTests/Info.plist

- Adds missing IOS build configs / Go_social.xcodeproj 
- Now able to open the Xcode project and do further configurations
- Currently, IOS build is missing and unable to open the xcodeproj
- closes #114

Adds missing IOS build / Go_social.xcodeproj

---

config/config.example.js

I have updated config.example.js file to include more specific instruction on building the app locally. It will make the instructions more precise and prevent any confusion. Fixes #118

Updated config.example.js

---

android/app/build.gradle

resolved this issue by updating the minSdkVersion to 21, as package="com.facebook.react" doesn't works for minSdkVersion=16.
Fixes #121

Upgraded minSdkVersion to 21

---

app/components/ForumBox/styles.js

fix for missing import of `Platform` in **forumbox/style.js**
modified `style.js `
- added import platform from react-native

platform import fix in forumbox/style.js
